server:
  port: 8999


eureka:
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
      - id: rvy-product-service
        uri: lb://rvy-product-service
        predicates:
          - Path=/rvy/api/**
