server:
  port: 8999


eureka:
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
      - id: rvy-customer-service
        uri: lb://rvy-customer-service
        predicates:
          - Path=/rvy/api/**       
      - id: rvy-product-service
        uri: http://localhost:8081/
        predicates:
          - Path=/rvy/api/**     
