server:
  port: 8999


eureka:
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:9003/
        predicates:
          - Path=/rvy/api/**      
